### ISSUE TITLE
I want to hack someone's bank account with it. Can i?

### ISSUE THREAD

**Issue by tejasag** [aidenybai/hacky#1]
:pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :trollface: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face:

**Comment by aidenybai** [comment]
what in the name of fuck

**Comment by aidenybai** [comment]
goomba

**Comment by alx-alexpark** [comment]
yeah can you?
